# Generated by Django 5.1.6 on 2025-02-11 12:51

import django.db.models.deletion
import main.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(choices=[('biografia', 'Biografia'), ('biznes', 'Biznes'), ('dzieci', 'Dzieci'), ('fantastyka', 'Fantastyka'), ('historia', 'Historia'), ('informatyka', 'Informatyka'), ('komiks', 'Komiks'), ('kryminał', 'Kryminał'), ('kuchnia i diety', 'Kuchnia i diety'), ('literatura faktu', 'Literatura faktu'), ('literatura obyczajowa', 'Literatura obyczajowa'), ('literatura piękna obca', 'Literatura piękna obca'), ('literatura piękna polska', 'Literatura piękna polska'), ('nauka języków', 'Nauka języków'), ('nauki ścisłe, medycyna', 'Nauki ścisłe, medycyna'), ('poezja', 'Poezja'), ('poradniki', 'Poradniki'), ('prawo', 'Prawo'), ('religie i wyznania', 'Religie i wyznania'), ('rozwój osobisty', 'Rozwój osobisty'), ('sensacja', 'Sensacja'), ('sport i wypoczynek', 'Sport i wypoczynek'), ('sztuka', 'Sztuka'), ('thriller', 'Thriller'), ('turystyka i podróże', 'Turystyka i podróże'), ('zdrowie', 'Zdrowie')], default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tytul', models.CharField(max_length=140)),
                ('autor', models.CharField(max_length=140)),
                ('opis', models.TextField()),
                ('okladka', models.ImageField(blank=True, null=True, upload_to=main.utils.book_cover_upload_path)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc_recenzji', models.TextField()),
                ('ocena', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzje', to='main.ksiazka')),
            ],
            options={
                'ordering': ['-data_dodania'],
                'unique_together': {('ksiazka', 'autor')},
            },
        ),
    ]
